#!/bin/sh

set -e

DOCKER_IMG=md-pdf

build() {
	DOCKER_BUILDKIT=1 docker build -t $DOCKER_IMG - <<EOF
        FROM pandoc/latex:3.1.1.0
        RUN <<EISVOGEL
            wget https://github.com/Wandmalfarbe/pandoc-latex-template/releases/download/v2.4.0/Eisvogel.zip -O /tmp/eisvogel.zip
            mkdir -p /pandoc/templates
            unzip -p /tmp/eisvogel.zip eisvogel.latex > /pandoc/templates/eisvogel.latex
            rm /tmp/eisvogel.zip
EISVOGEL
        RUN <<TLMGR
            tlmgr install \
            adjustbox \
            babel-french \
            background \
            bidi \
            catchfile \
            collectbox \
            collection-fontsrecommended \
            csquotes \
            everypage \
            filehook \
            footmisc \
            footnotebackref \
            framed \
            fvextra \
            hardwrap \
            koma-script \
            letltxmacro \
            lineno \
            ly1 \
            mdframed \
            minted \
            mweights \
            needspace \
            pagecolor \
            sectsty \
            sourcecodepro \
            sourcesanspro \
            titling \
            ucharcat \
            ulem \
            unicode-math \
            upquote \
            xecjk \
            xurl \
            zref
TLMGR
        RUN apk add --no-cache graphviz ttf-freefont
        RUN mkdir -p /pandoc/filters
        RUN wget https://raw.githubusercontent.com/pandoc-ext/diagram/main/_extensions/diagram/diagram.lua -O /pandoc/filters/diagram.lua
EOF
}

# Rebuild if needed
docker inspect $DOCKER_IMG >/dev/null 2>/dev/null || build
[ "$(date -d $(docker inspect -f '{{json .Metadata.LastTagTime }}' $DOCKER_IMG | tr -d '"') +'%s')" -lt "$(date -r $0 +'%s')" ] && build

run() {
	mkdir -p /tmp/dot_cache
	docker run --rm -i \
		-v .:/data -v /tmp/dot_cache:/tmp -u "$(id -u):$(id -g)" \
		"$DOCKER_IMG" \
		-f gfm -t pdf \
		--data-dir /pandoc \
		--template eisvogel \
		-V geometry:a4paper \
		-V geometry:margin=3cm \
		-V titlepage:true \
		-V diagram.cache:true \
		-V diagram.cache-dir:/tmp \
		--lua-filter diagram.lua \
		"$@"

	# docker exec -it container-name sh
}

show_help() {
	echo "Usage $0 [-h] [-m] file [other options]"
	echo " -h: show help"
	echo " -m: file is an HedgeDoc id"
}

# handle options
OPTIND=1

file_type="file"
while getopts "h?m" opt; do
	case "$opt" in
	h | \?)
		show_help
		exit 0
		;;
	m)
		file_type="hedgedoc"
		;;
	esac
done
shift $((OPTIND - 1))
[ "${1:-}" = "--" ] && shift
[ $# -eq 0 ] && show_help && exit 1

file=$1
shift

time (
	case "$file_type" in
	"file")
		echo "$file"
		run "$file" "$@"
		;;
	"hedgedoc")
		echo "https://hedgedoc.cri.epita.fr/$file"
		out_name=$(curl -s "https://hedgedoc.cri.epita.fr/$file/info" | jq -r .title | sed -e 's/[][$\/\]//g' -e 's/ /_/g' -e 's/$/\.pdf/')
		curl -s "https://hedgedoc.cri.epita.fr/$file/download" | run -o "$out_name" "$@"
		;;
	esac
)
